ae_dbt:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: postgres
      password: james
      port: 5432
      dbname: analytics
      schema: analytics_staging  # dbt will create if missing
      threads: 4

    duckdb:
      type: duckdb
      path: ./data/ae.duckdb
      schema: analytics_staging
      threads: 4
